### ISSUE TITLE
Wrong Affiliation 

### ISSUE THREAD

**Issue by annamartin-niedecken** [tjmonsi/chi-interactive-program-v2#17]
Hi there

May I kindly ask you to correct my affiliation to the online program (D201).

Incorrect: Anna Lisa Martin-Niedecken, Department of Design, Subject Area in Game Design
Correct: Anna Lisa Martin-Niedecken, Zurich University of the Arts

Thanks a lot and kind regards.
Anna

**Comment by tjmonsi** [comment]
Hi 

The data is automatically pulled from PCS, so they need to make the fix there, and that it unfortunately might be too late for CHI 2018.
