### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by samyuanx** [tjmonsi/chi-interactive-program-v2#23]
Search is not really working. After a query is entered, the loading state lasts forever and the results are unable to load.

**Comment by tjmonsi** [comment]
Hi @samyuanx 

I have to turn off the feature because it is costing me a bit (given that it uses Algolia), will try to figure out how I can use the free version without cost. So sorry about this.

**Comment by tjmonsi** [comment]
@samyuanx 

I reverted the indexing back... Hopefully it works now.
