### ISSUE TITLE
Dates are Wrong on Web Programme

### ISSUE THREAD

**Issue by nan-alonso** [tjmonsi/chi-interactive-program-v2#24]
Saturday is listed as "May 3rd", Sunday is listed as "May 4th" -- these are one day too early.

**Comment by tjmonsi** [comment]
Hi @nan-alonso thanks for letting us know. I'll tell it to our data chair

**Comment by tjmonsi** [comment]
Hi @nan-alonso i have figured that you might be at a timezone that is -1 day of +0 GMT. I have fixed the code so that it will just use the date given instead of using the computer's date system. Please close if it is fixed

**Comment by nan-alonso** [comment]
Oh good! I thought it might be a timezone thing. I did want to confirm
though since flight and lodging is booked!
