### ISSUE TITLE
search does not work (or take eons to complete)

### ISSUE THREAD

**Issue by nicolasgo** [tjmonsi/chi-interactive-program-v2#6]
Just tried to search any topic talking about usability.
Waited a minute before I closed the tab.

Nice animation though.

**Comment by tjmonsi** [comment]
Hmmmm. I would like to replicate this. What is your device and what are the search keyword that you have used.

**Comment by nicolasgo** [comment]
Mbp 2017
Keyword: usability

Enviado desde mi iPhone

El 26 mar 2018, a la(s) 21:23, Toni-Jan Keith Monserrat <notifications@github.com<mailto:notifications@github.com>> escribió:


Hmmmm. I would like to replicate this. What is your device and what are the search keyword that you have used.

**Comment by joolsa** [comment]
Search is really bad; trying to look for exact match "personas" in paper titles and getting variations like "personal". Also, author name "Yuta" gives matches like "Yuan". Sorry to say, but the search is completely useless. You should test these systems before putting them out.
