### ISSUE TITLE
Collapsing sections don't stay open

### ISSUE THREAD

**Issue by mchaput** [tjmonsi/chi-interactive-program-v2#9]
If I click a day to see the schedule on that day, after a certain amount of time the section will close again on its own.

Clicking the icons to the right of the section name seemed to open the section and immediately close it again, but that only seemed to happen after the page had gotten into some bad state, I don't think it was doing that initially.

**Comment by tjmonsi** [comment]
Yes, I got that as well and figured out the problem. Will fix it right away. Thanks for the headsup :)

**Comment by tjmonsi** [comment]
Fixed. Please close if it has been fixed on your side as well :)
